"""
Django settings for abb_inventory_system project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / '
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
import os

from dotenv import load_dotenv


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


ENVIRONMENT = os.environ.get("DJANGO_ENV", os.environ.get("ENVIRONMENT", "development")).strip().lower()

if ENVIRONMENT in {"prod", "production"}:
    load_dotenv(BASE_DIR / ".env.prod")
else:
    load_dotenv(BASE_DIR / ".env")

# Keep existing environment variables (e.g., Render/Railway/Cloud Run) higher priority than dotenv values.
load_dotenv(override=False)

SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    raise ValueError("SECRET_KEY is not set")

DEBUG = _env_bool("DEBUG", default=False)

ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    "127.0.0.1,localhost"
).split(",")

CSRF_TRUSTED_ORIGINS = [o.strip().strip('"').strip("'") for o in os.environ.get(
    "CSRF_TRUSTED_ORIGINS", ""
).split(",") if o.strip()]

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # If your production environment uses HTTPS (recommended):
    SECURE_SSL_REDIRECT = True

    # If you're behind a proxy/load balancer (Render, Nginx, Cloud Run, etc.)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Auto-logout after 30 minutes of inactivity for all session-based logins.
SESSION_COOKIE_AGE = 60 * 30
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Manager secret used to grant/revoke individual department access from login page.
# Set this in environment for production.
INVENTORY_MANAGER_GRANT_CODE = os.environ.get("INVENTORY_MANAGER_GRANT_CODE", "ABB-MANAGER")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventory',
]

USE_CLOUDINARY = bool(os.environ.get("CLOUDINARY_URL"))

if USE_CLOUDINARY:
    INSTALLED_APPS += [
        'cloudinary_storage',
        'cloudinary',
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'abb_inventory_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':[BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'abb_inventory_system.wsgi.application'

import dj_database_url

USE_LOCAL_SQLITE = _env_bool("USE_LOCAL_SQLITE", default=False)
LOCAL_DATABASE_URL = (os.environ.get("LOCAL_DATABASE_URL", "") or "").strip()

if USE_LOCAL_SQLITE:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASE_URL = (
        LOCAL_DATABASE_URL
        or os.environ.get("DATABASE_URL")
        or os.environ.get("PRODUCTION_DB")
        or os.environ.get("Production_db")
    )

    if not DATABASE_URL:
        raise ValueError(
            "DATABASE_URL is not set (accepted keys: DATABASE_URL, PRODUCTION_DB, Production_db) "
            "or set USE_LOCAL_SQLITE=1 for local development."
        )

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=not DEBUG,
        )
    }




# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

if USE_CLOUDINARY:
    CLOUDINARY_STORAGE = {
        'FOLDER': os.environ.get('CLOUDINARY_MEDIA_FOLDER', 'abb_inventory'),
    }

    STORAGES = {
        'default': {
            'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

    MEDIA_URL = os.environ.get('CLOUDINARY_MEDIA_URL', '')
    MEDIA_ROOT = ''
else:
    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }


# Base URL used to build links inside emails.
# Priority:
# 1) APP_BASE_URL explicit env
# 2) Common platform host envs
# 3) First non-local ALLOWED_HOSTS entry
# 4) Localhost fallback for development only
_app_base_url = (os.environ.get("APP_BASE_URL", "") or "").strip().strip('"').strip("'").rstrip("/")

if not _app_base_url:
    render_host = (os.environ.get("RENDER_EXTERNAL_HOSTNAME", "") or "").strip().strip('"').strip("'")
    railway_host = (os.environ.get("RAILWAY_PUBLIC_DOMAIN", "") or "").strip().strip('"').strip("'")
    if render_host:
        _app_base_url = f"https://{render_host}"
    elif railway_host:
        _app_base_url = f"https://{railway_host}"

if not _app_base_url:
    for host in ALLOWED_HOSTS:
        cleaned = host.strip().split(":")[0].lower()
        if cleaned and cleaned not in {"localhost", "127.0.0.1", "*"}:
            _app_base_url = f"{'http' if DEBUG else 'https'}://{cleaned}"
            break

APP_BASE_URL = _app_base_url or "http://127.0.0.1:8000"

# Email delivery settings (set these in .env/.env.prod for real inbox delivery).
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com").strip().strip('"').strip("'")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "").strip().strip('"').strip("'")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "").strip().strip('"').strip("'")
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", default=True)
EMAIL_USE_SSL = _env_bool("EMAIL_USE_SSL", default=False)

# Gmail App Passwords are often copied with spaces (e.g. "abcd efgh ijkl mnop").
# Normalize that into the value SMTP expects.
if EMAIL_HOST.lower() == "smtp.gmail.com":
    EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD.replace(" ", "")

raw_default_from_email = os.environ.get("DEFAULT_FROM_EMAIL", "").strip()

# Guard against accidentally placing Python code text in env var values on host dashboards.
# Example bad value: os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "noreply@...")
if raw_default_from_email.startswith("os.environ.get("):
    raw_default_from_email = ""

DEFAULT_FROM_EMAIL = raw_default_from_email or EMAIL_HOST_USER or "noreply@abb-inventory.local"




