# Generated by Django 6.0.2 on 2026-03-04 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSetupKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_admin_setup_key',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'inventory_building',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'inventory_manufacturer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Technical description or specifications')),
                ('image', models.ImageField(blank=True, null=True, upload_to='part_images/')),
            ],
            options={
                'db_table': 'inventory_part',
                'ordering': ['model_number'],
            },
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'inventory_user_email',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'inventory_vendor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='inventory.building')),
            ],
            options={
                'db_table': 'inventory_department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_code', to='inventory.department')),
            ],
            options={
                'db_table': 'inventory_department_access_code',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('location', models.CharField(help_text='Internal location inside department', max_length=100)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Idle', 'Idle'), ('Maintenance', 'Maintenance'), ('Down', 'Down')], default='Idle', max_length=20)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('uptime', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='machine_images/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='inventory.department')),
            ],
            options={
                'db_table': 'inventory_machine',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ManagerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('access_code_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departments', models.ManyToManyField(blank=True, related_name='manager_accounts', to='inventory.department')),
            ],
            options={
                'db_table': 'inventory_manager_account',
                'ordering': ['first_name', 'last_name', 'email'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField(blank=True)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('date_fixed', models.DateTimeField(blank=True, null=True)),
                ('time_to_fix', models.DurationField(blank=True, null=True)),
                ('part_consumed', models.BooleanField(default=False)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='inventory.machine')),
                ('part_replaced', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.part')),
            ],
            options={
                'db_table': 'inventory_maintenance_record',
                'ordering': ['-date_reported'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qr_payload', models.TextField(blank=True)),
                ('qr_image_url', models.URLField(blank=True)),
                ('qr_png', models.FileField(blank=True, null=True, upload_to='station_qr_images/')),
                ('qr_pdf', models.FileField(blank=True, null=True, upload_to='station_qr_pdfs/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='inventory.department')),
            ],
            options={
                'db_table': 'inventory_station',
                'ordering': ['department__name', 'name'],
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='inventory.station'),
        ),
        migrations.CreateModel(
            name='UserRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_description', models.TextField(blank=True)),
                ('name_of_requester', models.CharField(blank=True, max_length=100)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.department')),
            ],
            options={
                'db_table': 'inventory_user_requirement',
                'ordering': ['-date_reported'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_message', models.TextField(blank=True)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_order_notifications', to='inventory.machine')),
            ],
            options={
                'db_table': 'inventory_work_order_notification',
                'ordering': ['-date_reported'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=2)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('COMING', 'Coming'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20)),
                ('technician_first_name', models.CharField(blank=True, max_length=100)),
                ('technician_last_name', models.CharField(blank=True, max_length=100)),
                ('technician_email', models.EmailField(blank=True, max_length=254)),
                ('completed_by_first_name', models.CharField(blank=True, max_length=100)),
                ('completed_by_last_name', models.CharField(blank=True, max_length=100)),
                ('completed_by_email', models.EmailField(blank=True, max_length=254)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='inventory.department')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='inventory.machine')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='inventory.station')),
            ],
            options={
                'db_table': 'inventory_work_order_request',
                'ordering': ['scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentAuthorizedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_users', to='inventory.department')),
            ],
            options={
                'db_table': 'inventory_department_authorized_user',
                'ordering': ['department__name', 'first_name', 'last_name', 'email'],
                'unique_together': {('department', 'email')},
            },
        ),
        migrations.CreateModel(
            name='MachinePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_left', models.PositiveIntegerField(default=0)),
                ('placement_location', models.CharField(blank=True, max_length=200)),
                ('compatibility_notes', models.TextField(blank=True)),
                ('last_action_by_first_name', models.CharField(blank=True, max_length=100)),
                ('last_action_by_last_name', models.CharField(blank=True, max_length=100)),
                ('last_action_type', models.CharField(blank=True, max_length=30)),
                ('last_used_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('last_action_at', models.DateTimeField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.machine')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.part')),
            ],
            options={
                'db_table': 'inventory_machine_part',
                'unique_together': {('machine', 'part')},
            },
        ),
        migrations.CreateModel(
            name='VendorPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.manufacturer')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.part')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vendor')),
            ],
            options={
                'db_table': 'inventory_vendor_part',
                'unique_together': {('part', 'vendor')},
            },
        ),
    ]
