# Generated by Django 6.0.2 on 2026-02-24 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100, unique=True)),
                ('machine_type', models.CharField(max_length=100)),
                ('machine_location', models.CharField(max_length=100)),
                ('machine_status', models.CharField(max_length=100)),
                ('machine_last_updated', models.DateTimeField(auto_now=True)),
                ('machine_uptime', models.FloatField(default=0.0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='inventory.department')),
            ],
        ),
        migrations.CreateModel(
            name='MachinePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=100)),
                ('part_description', models.TextField(blank=True)),
                ('quantity_left', models.PositiveIntegerField(default=0)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('manufacturer_name', models.CharField(blank=True, max_length=120)),
                ('manufacturer_phone', models.CharField(blank=True, max_length=30)),
                ('vendor_name', models.CharField(blank=True, max_length=120)),
                ('vendor_phone', models.CharField(blank=True, max_length=30)),
                ('vendor_website', models.URLField(blank=True, max_length=300)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='inventory.machine')),
            ],
            options={
                'unique_together': {('machine', 'model_number')},
            },
        ),
        migrations.CreateModel(
            name='MachineMaintenanceTrackRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField(blank=True)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('date_fixed', models.DateTimeField(blank=True, null=True)),
                ('time_to_fix', models.DurationField(blank=True, null=True)),
                ('part_consumed', models.BooleanField(default=False)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='inventory.machine')),
                ('part_replaced', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='inventory.machinepart')),
            ],
        ),
        migrations.CreateModel(
            name='User_Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_description', models.TextField(blank=True)),
                ('name_of_requester', models.CharField(blank=True, max_length=100)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requirements', to='inventory.department')),
            ],
        ),
    ]
