# Generated by Django 6.0.2 on 2026-02-25 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(db_index=True, max_length=100)),
                ('part_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('part_image', models.ImageField(blank=True, null=True, upload_to='part_images/')),
                ('usage_description', models.TextField(blank=True, help_text='What this part is used for')),
            ],
            options={
                'ordering': ['model_number'],
            },
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='inventory.building')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100, unique=True)),
                ('machine_type', models.CharField(max_length=100)),
                ('machine_location', models.CharField(max_length=100)),
                ('machine_image', models.ImageField(blank=True, null=True, upload_to='machine_images/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='inventory.department')),
            ],
            options={
                'ordering': ['machine_name'],
            },
        ),
        migrations.CreateModel(
            name='MachineMaintenanceTrackRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField(blank=True)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('date_fixed', models.DateTimeField(blank=True, null=True)),
                ('time_to_fix', models.DurationField(blank=True, null=True)),
                ('part_consumed', models.BooleanField(default=False)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='inventory.machine')),
                ('part_replaced', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='inventory.part')),
            ],
            options={
                'ordering': ['-date_reported'],
            },
        ),
        migrations.CreateModel(
            name='UserRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_description', models.TextField(blank=True)),
                ('name_of_requester', models.CharField(blank=True, max_length=100)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requirements', to='inventory.department')),
            ],
            options={
                'ordering': ['-date_reported'],
            },
        ),
        migrations.CreateModel(
            name='MachinePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_left', models.PositiveIntegerField(db_index=True, default=0)),
                ('placement_location', models.CharField(blank=True, help_text='Where the part is installed in the machine', max_length=200)),
                ('compatibility_notes', models.TextField(blank=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_parts', to='inventory.machine')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_parts', to='inventory.part')),
            ],
            options={
                'ordering': ['machine'],
                'unique_together': {('machine', 'part')},
            },
        ),
        migrations.CreateModel(
            name='VendorPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.manufacturer')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_links', to='inventory.part')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_links', to='inventory.vendor')),
            ],
            options={
                'ordering': ['part'],
                'unique_together': {('part', 'vendor')},
            },
        ),
    ]
