# Generated by Django 6.0.2 on 2026-03-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_workorderrequest_machine_running_after_repair'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderrequest',
            name='total_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Total minutes (rounded, payroll style)', null=True),
        ),
    ]
